### ISSUE TITLE
Unity Editor crashes on play

### ISSUE THREAD

**Issue by halfpasttense** [ValveSoftware/unity-xr-plugin#1]
Running Unity version 2019.4.0f1. I just updated the OpenVR XR Plugin package from preview.2 to preview.4, and now it crashes every time I hit play, whereas before on preview.2 it worked fine. I'm using a Valve Index for testing, and it is plugged in and active when I hit play. I've had to go back to preview.2 until this is fixed.

**Comment by halfpasttense** [comment]
[Editor-prev.log](https://github.com/ValveSoftware/unity-xr-plugin/files/4835341/Editor-prev.log)
Attaching editor log with crash.

**Comment by halfpasttense** [comment]
[SteamVR-2020-06-26-AM_02_17_25.txt](https://github.com/ValveSoftware/unity-xr-plugin/files/4835362/SteamVR-2020-06-26-AM_02_17_25.txt)
Also attaching SteamVR system report. However this was not collected directly after the crash. Only later when I downgraded to preview.2 and checked it to be working again. It was however collected during the same run of SteamVR as the crash. (I never shut down SteamVR after the crashes.)

**Comment by zite** [comment]
It looks like the OpenVR Init call is returning Init_InterfaceNotFound. Does your SteamVR, or headset need an update? You might also try opting in to SteamVR Beta.

**Comment by halfpasttense** [comment]
> It looks like the OpenVR Init call is returning Init_InterfaceNotFound. Does your SteamVR, or headset need an update? You might also try opting in to SteamVR Beta.

That was the problem. It needs the SteamVR beta to work. You might want to mention that in your instructions. 

But now I see input through the XR Input system no longer works.. even though it used to work in preview.2. I have no intention of going back to using the SteamVR plugin for input so I guess again I'll have to go back to preview.2. Why would you remove something that was already working?

**Comment by zite** [comment]
This has been fixed in preview-5. Thanks for the report!

Input wasn't really working correctly in preview.2 either. Instead of continuing to work on a legacy system we're reorienting around OpenXR. See this blog post for more info: https://steamcommunity.com/games/250820/announcements/detail/2522527900755718764
