### ISSUE TITLE
updated to preview.5 from preview.4 and editor crashes on play

### ISSUE THREAD

**Issue by dshewmaker** [ValveSoftware/unity-xr-plugin#12]
Hello,
[Crash_2020-07-17_152924469.zip](https://github.com/ValveSoftware/unity-xr-plugin/files/4938685/Crash_2020-07-17_152924469.zip)

Here are the crash dmp and log files.  Updated and editor crashes when play.

**Comment by kisak-valve** [comment]
For reference, the attached minidump is an EXCEPTION_ACCESS_VIOLATION_READ in XRSDKOpenVR.dll.

**Comment by zite** [comment]
Does this continue happening after restarting the editor?

**Comment by dshewmaker** [comment]
Hello, I will try get that updated tonight and if not for sure tomorrow morning.

It does happen after restarting the editor.

**Comment by dshewmaker** [comment]
@zite After updating it does not crash the editor.

**Comment by zite** [comment]
Great, thanks for the initial report and update. We've just pushed preview-7 which fixes the meta file issue as well.
