### ISSUE TITLE
Can I make xr interaction toolkit action based work with open vr loader

### ISSUE THREAD

**Issue by stranger-games** [ValveSoftware/unity-xr-plugin#125]
Hi,

I have setup my game using openxr and xr interaction toolkit and everything works fine with all devices with action based rig.

However, I want steam vr support so that steam build can show steam vr menu and do in app purchases within the VR game.
Without the OpenVR loader, in app purchase window appear on desktop and the left controller menu button doesn't open the steam window.

So I added steamvr from the asset store which added the package for openvr and enabled openvr loader.
Once I did this, the action based xr rig doesn't respond to headset or controller movement.

I tried device based rig and it worked, but I don't want to reset everything to device based after I created it action based.
Is there a way to make the rig which is action based to work with open vr loader enabled?
Or leave open vr loader disabled but make the micro transaction window appear in VR like it normally does with steam vr games?

Thanks for advance.

**Comment by zite** [comment]
IAP should work via the steamworks api: ISteamFriends::ActivateGameOverlayToStore If there was previously a bug in it I think its been fixed now. Let me know if that's not true.
