### ISSUE TITLE
using WMR(Windows Mixed Reality) Samsung Odyssey, OpenVR cannot be installed!

### ISSUE THREAD

**Issue by ll-M-ll** [ValveSoftware/unity-xr-plugin#13]
Hello,

I've tried it on version **2019.3.7f** and **2020.1.0BETA**

**How did I Install the package:**

1 - **Package manager > Add package from disk...**
2 - **SteamVR2.6Beta**: is from the Asset CustomPackage then stopped the Auto Enable VR ( which would turn on the depreciated version of openVR ) I just went to  **Assets -> SteamVR_Resources -> Resources** and turned it off from there.

The scene was  just a plane with **Room-scale XR-Rig**
* no other assets was in the scene 
* windows 10 + Samsung Odyssey (**Windows mixed reality** )

**2019.3.7f**

After enabling the OpenVR loader and hitting the play button

SteamVR was launched to run the Scene ....

workaround it was me adding Windows mixed reality loader underneath it and that ran the scene on windows mixed reality

**2020.1.0Beta**
so what I have done was that I downloaded the package  
while trying to Enabling the OpenVr Loader I got this error 

`_Package Metadata store error. Check if there are any other errors in the console and make sure they are corrected before trying again.
 Failure reason: Error installing package com.valve.openvr. Error Code: Failure Error Message: Unable to add package [com.valve.openvr]:
  Package [com.valve.openvr] cannot be found
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()_
`

again I was able to run the scene with windows mixed reality loader.

* many times after I save the scene and relaunch Unity, even WMR stops from working, always runs on steamVR *

-------------------------------------------------------------------------------------------------------------------------------------------
**Update:** - **work Around (( FAILED )) X X** 

When I've disconnected the Headset on version **2020.1.0BETA** I was able to turn on the "**OpenVR Loader**" but when I launched the scene after that I got this Message.

` static Void PreferencesGUI() does not match UnityEditor.SettingsProviderAttribute expected signature.
 Use static UnityEditor.SettingsProvider signature()
UnityEditor.SettingsWindow:OnEnable()` 

and SteamVR was launched even though I had  **Windows mixed reality**  Enabled underneath the **OpenVR Loader** , So I guess it just Skipped it.
------------------------------------------------------------------------------------------------------------------------------------------

New Warning/Error  appeared to be blocking many other scripts

` SteamVR] Initialization failed. OpenVR is not in your list of supported virtual reality SDKs. Add it to the list in player settings. To force OpenVR initialization call SteamVR.Initialize(true). 
UnityEngine.Debug:LogWarning(Object) `

I can't even to run 'Debug.log("updated");' on the start or the update function, Nothing works

**Comment by zite** [comment]
I think you may be upgrading XR Management Tools instead of our plugin. You want to upgrade the package named OpenVR XR Plugin. If there isn't an option to upgrade you need to click "Remove" in the package manager, then open the installer from the link above.
If you're also using the SteamVR Unity Plugin then you'll need to upgrade that to the latest beta, found here: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.6.0b3

**Comment by ll-M-ll** [comment]
![image](https://user-images.githubusercontent.com/43939767/87851267-6bd7bf00-c8f7-11ea-9d05-2e955eeb8dc1.png)
So i did exactly that, I've removed the openVR plugin, 

and this is what happened after installing Steam open VR b3 

![image](https://user-images.githubusercontent.com/43939767/87851529-e570ac80-c8f9-11ea-84c6-74fc4dcbaac2.png)


errors keep on popping up and whenever OpenVR is selected SteamVR launches instead ...

**Comment by zite** [comment]
There was a combination of critical errors between our debug dlls and unity's xr management 3.2.10. Updating to the newest preview.9 (at time of writing) this issue should be resolved.

**Comment by ll-M-ll** [comment]
@zite well i dont know what to say.
once I've installed preview 9 and preview 10 after both of them had this constant compiler error
`Assets\SteamVR\Scripts\SteamVR_Menu.cs(175,36): error CS1061: 'CVRSystem' does not contain a definition for 'ResetSeatedZeroPose' and no accessible extension method 'ResetSeatedZeroPose' accepting a first argument of type 'CVRSystem' could be found (are you missing a using directive or an assembly reference?)
`

I'm using 2019.3

**Comment by ll-M-ll** [comment]
followed by 4 errors that can becleared but here

`Asset Packages/com.valvesoftware.unity.openvr/Runtime/x64/openvr_api.pdb has no meta file, but it's in an immutable folder. The asset will be ignored.`

`Asset Packages/com.valvesoftware.unity.openvr/Runtime/x64/openvr_api.pdb has no meta file, but it's in an immutable folder. The asset will be ignored.`

`Asset Packages/com.valvesoftware.unity.openvr/Runtime/x64/XRSDKOpenVR.pdb has no meta file, but it's in an immutable folder. The asset will be ignored.
`

`Asset Packages/com.valvesoftware.unity.openvr/Runtime/x86/openvr_api.pdb has no meta file, but it's in an immutable folder. The asset will be ignored.
`

`Asset Packages/com.valvesoftware.unity.openvr/Runtime/x86/XRSDKOpenVR.pdb has no meta file, but it's in an immutable folder. The asset will be ignored.
`

**Comment by ll-M-ll** [comment]
I am ready to launch my application on EpicGames now using XR, SteamVR is my only obstacle on launching it on steam.
maybe steamVR is really depreciated for good.

**Comment by ll-M-ll** [comment]
![image](https://user-images.githubusercontent.com/43939767/88600897-9c45f880-d06f-11ea-90cd-80b7eaecc22f.png)
I've changed the code on line 175: from `system.ResetSeatedZeroPose();` to `system.GetSeatedZeroPoseToStandingAbsoluteTrackingPose();` as you can see in the image, the issue is gone but I've no Idea if that have fixed the issue or will cause more problems.

here my package manger 
![image](https://user-images.githubusercontent.com/43939767/88601055-09f22480-d070-11ea-9826-7eb2d5a2aaf3.png)

looks like the 5 errors are gun I only have few warnings and this message keeps on poping but it doesn't stop me from going into the play mode

`static Void PreferencesGUI() does not match UnityEditor.SettingsProviderAttribute expected signature.
 Use static UnityEditor.SettingsProvider signature()
UnityEditor.SettingsWindow:OnEnable()`

**Comment by zite** [comment]
It looks like you have some leftovers from previous installs. I'd recommend deleting the assets/steamvr folder and reimporting beta3 of the steamvr unity plugin.

Although, we are recommending people don't ship things with these preview versions. But of course it's up to you.

**Comment by zite** [comment]
> I am ready to launch my application on EpicGames now using XR, SteamVR is my only obstacle on launching it on steam.
> 
> maybe steamVR is really depreciated for good. 

I don't really understand what you mean here. How is the store impacting the API you're using? What is "XR"?

**Comment by ll-M-ll** [comment]
@zite I believe i must use SteamVR for vr games on steam.
but either way, I was trying to release the game that works on both systems with a little checker.

**Comment by zite** [comment]
What API were you using on EpicGames? You aren't required to use the SteamVR API on Steam, though we do encourage it. That said it looks like we're debugging what's left of the issues you're facing on another thread. So I'll close this one.
