### ISSUE TITLE
Steam VR Won't Open On Play

### ISSUE THREAD

**Issue by TenBitNet** [ValveSoftware/unity-xr-plugin#14]
Me and a friend are collaborating on a project. We have gone as far as to sending the file over the internet to start up the project. For some reason his opens steam vr and allows him to play through steam while mine doesn't. For the record I'm using a valve index. What steps should I take to make the steam vr and unity's xr plugin work together?

**Comment by zite** [comment]
Do you have the project files synced in whatever version control you're using? My best guess would be that the OpenVR Loader is not selected in your project on the XR-Plugin Management section of Project Settings. If that's not it can you send me an editor log from unity after you try to play a scene that should open vr? ( %LocalAppData%\Unity\Editor\Editor.log )

**Comment by TenBitNet** [comment]
We are using unity's collab but we have also attempted to share the files directly from each computer through mega files. Neither seem to allow the me to start steam vr.
[Editor.log](https://github.com/ValveSoftware/unity-xr-plugin/files/4951329/Editor.log)
![unknown](https://user-images.githubusercontent.com/32795492/88013345-2b8c6280-caea-11ea-945f-f61fdbec27aa.png)

**Comment by zite** [comment]
We may have fixed the issue in preview-7, can you update to that and let me know if it fixes the issue?

**Comment by TenBitNet** [comment]
[Editor(1).log](https://github.com/ValveSoftware/unity-xr-plugin/files/4957460/Editor.1.log)
Still unable to start up in steam vr sadly.

**Comment by zite** [comment]
It doesn't look like the package updated successfully for you. Can you try updating to preview.9? If it still fails, please send another editor log.

**Comment by TenBitNet** [comment]
Thanks so much it works now!
