### ISSUE TITLE
Plugin Usability

### ISSUE THREAD

**Issue by gkapellmann** [ValveSoftware/unity-xr-plugin#17]
Hello, 

Its probably more a question than an issue, and yet I also think is a bit of an issue.

Based on the description of this plugin: "If you would like input in your application please install the SteamVR Unity Plugin"

What is the point of having the plugin separate to "SteamVR" if the input is not going to be implemented? As I've seen things move to the OpenXR direction, right?

So besides rendering, is there any other use of this plugin on its own?

Thank you!

**Comment by zite** [comment]
This specific plugin is for the OpenVR API. Some applications only need rendering so we've split the rendering (which is Unity XR compatible) into this plugin, and are keeping SteamVR Input in the SteamVR Unity Plugin. If you install the SteamVR Unity Plugin on Unity 2020.1+ it will automatically install this package, the part you need to make Unity XR work.

We're big proponents of OpenXR. Any future OpenXR work will happen outside this plugin.
