### ISSUE TITLE
"XRSDKOpenVR.ilk has no meta file, but it's in an immutable folder" warning spam

### ISSUE THREAD

**Issue by CircuitLord** [ValveSoftware/unity-xr-plugin#18]
Currently, whenever any sort of script recompilation happens, this warning shows up.
"Asset Packages/com.valvesoftware.unity.openvr/Runtime/x86/XRSDKOpenVR.ilk has no meta file, but it's in an immutable folder. The asset will be ignored."

It doesn't actually affect the project's ability to compile, it just gets spammed everytime script recompilation happens. I've been able to fix it by moving the package into development mode so that the meta file generates properly.

Happens in Unity 2019.4 LTS and 2020.1 beta.

**Comment by zite** [comment]
Hi, in the Unity Package Manager try updating to the latest version of the preview to fix this. I believe we're on preview 10 currently.

**Comment by CircuitLord** [comment]
Yep, my bad, that seems to be working properly in preview 10 now, thanks!
