### ISSUE TITLE
Even though my project is working I always get the exception:"DllNotFoundException: XRSDKOpenVR"

### ISSUE THREAD

**Issue by Elelana** [ValveSoftware/unity-xr-plugin#22]
I'm using OpenVr preview 11, I'm always getting the exception:

DllNotFoundException: XRSDKOpenVR
Unity.XR.OpenVR.OpenVRLoader.Initialize () (at Library/PackageCache/com.valvesoftware.unity.openvr@1.0.0-preview.11/Runtime/OpenVRLoader.cs:183)
UnityEngine.XR.Management.XRManagerSettings.InitializeLoaderSync () (at Library/PackageCache/com.unity.xr.management@3.2.13/Runtime/XRManagerSettings.cs:169)
UnityEngine.XR.Management.XRGeneralSettings.InitXRSDK () (at Library/PackageCache/com.unity.xr.management@3.2.13/Runtime/XRGeneralSettings.cs:175)
UnityEngine.XR.Management.XRGeneralSettings.AttemptInitializeXRSDKOnLoad () (at Library/PackageCache/com.unity.xr.management@3.2.13/Runtime/XRGeneralSettings.cs:148)

How do I solve it? The .dll does not have any missing dependencies.
Thanks for help!

**Comment by zite** [comment]
That's very strange. What version of unity are you on?

**Comment by Elelana** [comment]
I deinstalled OpenVr Desktop, OpenVr xr Plugin and Xr Managemant, closed unity, restarted it, reinstalled the packages to the latest update on unity 2019.4.5 and the exception was gone. Thanks! Im using steamVR 1.13.10.
