### ISSUE TITLE
SteamVR Unity Plugin v2.2.0 / Unity 2020.1.0f1 incompatibility - builds are broken

### ISSUE THREAD

**Issue by guiglass** [ValveSoftware/unity-xr-plugin#25]
I just updated the Unity version in my SteamVR game to 2020.1.0f1 and had to install the unofficial xr plugin from github to support OpenVR.

Now I can only play my game in the editor and it works. But when I build my game it is totally messed up!!

In Editor:
![](https://i.imgur.com/1aaINvz.png)

In Final Build:
![](https://i.imgur.com/GJNAab4.png)

Even the Unity splash screen is all skewed when i first launch my final game. And the image seen here is stuck in the HMD and does not change, only streaks appear as I look around.

What can I do to fix this?

Please can somebody help!!

**Comment by 1runeberg** [comment]
Hi @guiglass - are you able to share your Player log for the build?

**Comment by guiglass** [comment]
I have just emailed you the log file. 


I have tested both single pass and multi pass rendering but both are the same in the final build. 

Also I am using SteamVR Unity Plugin - v2.2.0

Please let me know if there is any other information you need and thank you for investigating this issue!!

**Comment by zite** [comment]
To use Unity 2020.1 you'll need to use the beta version of steamvr_unity_plugin referenced in the readme here. It is still in beta though, we don't recommend shipping titles with it yet. https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.6.0b4
