### ISSUE TITLE
Dependency versions conflict

### ISSUE THREAD

**Issue by StefanJanssen95** [ValveSoftware/unity-xr-plugin#26]
I just downloaded the latest version of the OpenVR XR Plugin (version 1.0.0 preview.12) and it lists 3 dependencies
 > XR Plugin Management 3.2.13
 > Unity UI 1.0.0
 > XR Legacy Input Helpers 1.0.0

XR Plugin Management 3.2.13 shows an conflicting error
 > An error occurred while resolving packages:
  Package com.unity.xr.management@3.2.13 has invalid dependencies:
    com.unity.xr.legacyinputhelpers: Resolved version [1.0.0] does not satisfy requested version [2.1.2]

Using Unity 2020.1

**Comment by zite** [comment]
That’s strange, seems like the package manager should auto update that.

Can you manually update the legacy input helpers package in the package
manager window?

**Comment by StefanJanssen95** [comment]
> That’s strange, seems like the package manager should auto update that. Can you manually update the legacy input helpers package in the package manager window?

Updating it from the package manager only allows me to go up to 1.3.11 and tells me the project might break.
I did just see that when you expand the package in the package manager it allows you to select a specific version and 2.1.4 is visible there but not "verified". Which might be the reason it did not auto update. The error has gone, I will test on a later date if things were actually solved by this.

**Comment by zite** [comment]
That's strange, 2.1.4 shows as verified for me. In any case I'm changing the dependency to reference the newer version.
