### ISSUE TITLE
Error CS0433  on the 'OpenVR' type (exists in both SteamVR & Unity.XR.OpenVR)

### ISSUE THREAD

**Issue by LarrxX** [ValveSoftware/unity-xr-plugin#28]
Ever since the August 3rd update, I'm unable to use the `OpenVR.IsHmdPresent()` method (I use it to intialize Unity XR with either OpenVRLoader or MockHMDLoader). When I try to use `OpenVR.IsHmdPresent()` I get the following compilation error:

`Error	CS0433	The type 'OpenVR' exists in both 'SteamVR, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Unity.XR.OpenVR, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'`

I didn't have this problem with the previous version of the OpenVR XR Plugin, that supported Legacy Input (because I hadn't had the need to import the Steam VR Plugin then).

**Comment by zite** [comment]
I believe the readme says to use the asset store version of the SteamVR Unity Plugin but you'll actually need to use the beta release here for now: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.6.0b4

Let me know if this fixes the problem.

**Comment by LarrxX** [comment]
version 2.6.1 hit the asset store yesterday, so I tried that this morning. No more compile error, yay!

But inputs don't work anymore :'(

Unity XR doesn't receive any axis or button inputs, even though I did generate the default Steam Input files.

**Comment by LarrxX** [comment]
I just tested a clean new project, and still no input. I'm opening a new issue, this one can be closed

**Comment by kisak-valve** [comment]
Closing per the last comment.
