### ISSUE TITLE
OpenVR Desktop package keeps automatically re-installing

### ISSUE THREAD

**Issue by LarrxX** [ValveSoftware/unity-xr-plugin#30]
If I install this plugin and the Steam VR Plugin (to have access to buttons input), the OpenVR Desktop Packege keeps installing automatically. The package is unneeded since I'm using Unity XR.

What's wores, if I try to remove the OpenVR from the deprectaed Player Settings, or try to uncheck the "Virtual Reality Supported" box, it is automatically rechecked, and the SDK reinstalled:

![image](https://user-images.githubusercontent.com/16936069/89504816-f14ce180-d7c8-11ea-9801-fafe024eb13f.png)

Using Unity version 2019.4.5f1.

(might be the cause for issue #29 ?)

**Comment by LarrxX** [comment]
My bad, seems you just need to deactivate the "Force Enable VR" in SteamVR_settings.

**Comment by zite** [comment]
If you use the installer in the releases section of this plugin it should automatically uninstall OpenVR Desktop and install OpenVR XR Plugin.
