### ISSUE TITLE
Any Valve controller works with New Unity input system right now in unity 2020.1

### ISSUE THREAD

**Issue by Extrys** [ValveSoftware/unity-xr-plugin#32]
Any Valve controller works with New Unity input system right now in unity 2020.1
even in the input analyzer

**Comment by zite** [comment]
Is this with a different package? We don't have input system support in this package.

**Comment by Extrys** [comment]
oh I see, I had to implement a structure for supporting switching between input systems easy
I have to use SteamVR for Steam and unity Input System for Oculus and Oculus Quest
right now this is crazy how unity is going, I hope OpenXR support soon from unity because I see Valve is supporting OpenXR Right now

**Comment by streunerlein** [comment]
@Extrys would love to see your „structure“, do you mind sharing?

**Comment by Extrys** [comment]
Off course I will send part of the code here

But is basically

Two classes that has the same accessing interface so I just switch with
compilation rule what one I want to use so the accessing is the same
Also I had to modify the steamVR plugin to add a listener disposal feature

It's actually functional but stills on development
Anyways I don't think I will continue improving it because of the comming
OpenXR
