### ISSUE TITLE
SteamVR Actions not working in build.

### ISSUE THREAD

**Issue by hass101** [ValveSoftware/unity-xr-plugin#34]
Hi, I am using Unity 2019.4.8f1 and I have this plugin installed alongside the b4 version of the SteamVR plugin. I have behaviour pose scripts attached to my controllers and the bindings are working correctly inside the editor. However when I build the application for Windows, the actions including the pose do not work.

**Comment by zite** [comment]
We did a full release recently, probably best to give that a try. Delete the SteamVR directory from your assets folder and install the plugin from the unity asset store.

**Comment by hass101** [comment]
Hi, thanks I was originally having issues with that version, where if the controller was turned on after the app had started, then the input wasn't working at all and that's why I switched. However I have created a blank project, built one of the demo scenes and it appears to be working correctly. This means that there must be something wrong with my project, of which I was updating, so I will have another go at getting it to work.
thanks

**Comment by hass101** [comment]
Hi, I ended up removing the XR plugin management, this plugin and all of the SteamVR related folders. I then enabled the deprecated virtual reality settings and reimported the SteamVR plugin, of which then installed the OpenVR Desktop package. Everything is working now so I will just hold off from using the XR plugin management until a final release of the OpenXR plugin is released.
thanks
