### ISSUE TITLE
default UI select button not working with OpenVR plugin

### ISSUE THREAD

**Issue by lashman1985** [ValveSoftware/unity-xr-plugin#37]
when using the built-in XR plugins (for WMR and Oculus) - i can just use the built-in XR rigs with Unity's UI system no problem .. but when i switch to the OpenVR plugin suddenly i can no longer select anything in the UI ... i can still see the line rendering ray, the buttons still get highlighted when i hover over them, but when i press the trigger (or any other button) - nothing happens 

this happens on WMR, Vive, and even Index 

(i should probably add that i'm using HDRP ... but again, it works just fine when using the build-in WMR and Oculus plugins, only breaks using this one)

**Comment by zite** [comment]
Input is not supported through Unity's XR API. You'll need the SteamVR Unity Plugin for that. See this thread for more information: https://github.com/ValveSoftware/unity-xr-plugin/issues/16
