### ISSUE TITLE
Enable detecting if user is present in the headset through the Unity XR InputDevice API

### ISSUE THREAD

**Issue by cameronfeng** [ValveSoftware/unity-xr-plugin#43]
`{InputDevice}.TryGetFeatureValue(CommonUsages.userPresence, out bool isPresent)`

The above method doesn't work as expected and will always return false.

**Comment by zite** [comment]
Thanks for the report. Fixed in https://github.com/ValveSoftware/unity-xr-plugin/commit/9215e5c31a65083c8f368456b427100c9014295a

Should be in the next version.

**Comment by zite** [comment]
Hi again, thanks for reporting the issue. This should be fixed in the latest release. You're welcome to give it a try and let us know if it solves the problem.
https://github.com/ValveSoftware/unity-xr-plugin/releases/tag/v1.1.1b

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by lejeanf** [comment]
bump.

I use 
- OculusXR  Plugin 3.0.2
- OpenXR Plugin 1.4.2
- XR Core Utilities 2.0.0
- XR Interaction Toolkit 2.2.0
- XR Legacy input helpers 2.1.9
- XR Plugin Managment 4.2.0

Unity 2021.3.7f1 - URP
Build target Android

I am trying to use userpresence but run into some issues.
If i am in the editor and hit play, userpesence work.
If I build and launch the game in the oculus quest 2 userpresence does not work.
If i then run the build and run unity and plug the cable from oculus to the pc userpresence works.

I need userpresence to work autonomously from the computer, any ideas?

`using UnityEngine;
using UnityEngine.XR;

public class XRDevice
{
    private static InputDevice headDevice;
    public XRDevice()
    {
        if (headDevice == null)
        {
            headDevice = InputDevices.GetDeviceAtXRNode(XRNode.Head);
        }
    }

    /// <summary>
    /// returns true if the HMD is mounted on the users head. Returns false if the current headset does not support this feature or if the HMD is not mounted.
    /// </summary>
    /// <returns></returns>
    public static bool IsHMDMounted()
    {
        
        if (headDevice == null || headDevice.isValid == false)
        {
            headDevice = InputDevices.GetDeviceAtXRNode(XRNode.Head);
        }
        if (headDevice != null)
        {
            bool presenceFeatureSupported = headDevice.TryGetFeatureValue(CommonUsages.userPresence, out bool userPresent);
            if (headDevice.isValid && presenceFeatureSupported)
            {
                return userPresent;
            }
            else
            {
                return false;
            }
        }
        else
        {
            return false;
        }
    }
}`
