### ISSUE TITLE
XRMath.cpp/.h copyright/license?

### ISSUE THREAD

**Issue by rpavlik** [ValveSoftware/unity-xr-plugin#44]
Wondering the license/copyright status of `CommonHeaders/ProviderInterface/XRMath.cpp` and `XRMath.h`. The README says files in that directory are Unity Companion License and copyright Unity, but unlike the others in there, that one lacks copyright notices or license notices, is only included by code in Providers, and generally looks more like Valve code than Unity headers :)

Thanks for the clarification!

**Comment by zite** [comment]
It is indeed Unity Companion License as the README suggests

**Comment by rpavlik** [comment]
awesome, thanks for the quick response.
