### ISSUE TITLE
OpenVR Input core busted to hell

### ISSUE THREAD

**Issue by zezba9000** [ValveSoftware/unity-xr-plugin#45]
The original OpenVR input system was designed correctly as a low lever C/C++ interface that could be queried similar to a keyboard or mouse without insane abstractions that don't apply to most games or those games implement their own portable ones. Abstraction APIs like gestures etc should not be part of a low level API which leads to incompatibilities and portability issues as we have seen for a year or more now.

When will the over-engineered OpenVR input C interface be fixed to something like it was before?

**Comment by zite** [comment]
Along with many of our industry partners we've decided actions are the way to go to minimize cross-headset difficulties for the end user. For more information you can see this issue: https://github.com/ValveSoftware/unity-xr-plugin/issues/16

**Comment by zezba9000** [comment]
Sorry for the rant but this is just so frustrating.

Are the executives API designers now? Who comes up with this? Reminds me of Web-World scatter brained ideas.

In what world does a driver API not expose the actual non-abstracted input data from a peripheral that you can query for? (aka mouse, keyboard, DirectInput, XInput, etc, etc).
Have your input "action base" abstraction API just that... an abstraction and expose the raw input data we all know the openvr drivers are providing so we can continue to use our own abstractions. This also solves the UnityXR issue and doesn't hinder your own goals.

This is like abstraction logic 101... I really don't know how this has been messed up for this long.  I only ever use the Legacy Input.  OpenXR action system is over-engineering (don't copy it). Just like OpenGL and Vulkan will never unify all platforms under a single API neither will OpenXR.

**Comment by BrainSlugs83** [comment]
Seems like a strong violation of the "single responsibility" design pattern.  What you're describing should really be its own project or add-on that sits on top of the raw input.

**Comment by zezba9000** [comment]
@BrainSlugs83 What I'm describing has been a principle in agnostic driver APIs for the last 30 years.

For example you can make a specific Mouse driver for Windows but the agnostic Win32 C API you use to access it doesn't force you to use string/name based actions or require external config files to query. Its simply exposes input data you can poll or query and leaves up any "action" based notions to your implementation. This is how the OpenVR Legacy input system works as well that SHOULD NEVER be considered legacy and just improved.

**Comment by BrainSlugs83** [comment]
I absolutely agree -- like I said -- it seems like the way they're designing this goes against industry standards and best practices.

**Comment by aWeinhold** [comment]
And we all know where it ends... If they lose interest, because it becomes such a big monolith, clunky peace of software they throw it away, ask the marketing department for a new cool name, print it on it, and start a new version. For sure, it will not be compatible with the old one. I have seen that now soo many times, I get tiered of this, especially in the unity world. I get always the idea that so many programmers need work, so a lean and clean solution would be to less work for them... :(
