### ISSUE TITLE
FileSystemWatcher usage causes assert with il2cpp

### ISSUE THREAD

**Issue by rpavlik** [ValveSoftware/unity-xr-plugin#48]
In a sample app (in this case, based on the URP template, but I don't think it matters) and using the installer/updater package provided (which installed 1.0.1), a development build on/for windows causes the following assert:

![screenshot 29](https://user-images.githubusercontent.com/61129/93911973-c2cb8d00-fcc8-11ea-8f1b-12fec72cb210.png)

I hit this in Unity 2019.3.15f1, but based on comparing the file referenced, I think this would also happen in the latest version I just installed, 2020.1.6f1

**Comment by zite** [comment]
Hrm, filesystemwatcher shouldn't be in use on builds. We'll look into it.

**Comment by zite** [comment]
Thanks for the report! It was actually supposed to be in builds, I was thinking of something else. Switched to manual filesize watching instead. Fixed in https://github.com/ValveSoftware/unity-xr-plugin/commit/e7a476b930ee31ba7ed33c863a74900123a431ba

**Comment by rpavlik** [comment]
thanks!

**Comment by zite** [comment]
This should be fixed in the latest release. You're welcome to give it a try and let us know if it solves the problem.
https://github.com/ValveSoftware/unity-xr-plugin/releases/tag/v1.1.1b

**Comment by kisak-valve** [comment]
Closing per the last comment.
