### ISSUE TITLE
Valve index controller interaction issue (Cant grab objects)

### ISSUE THREAD

**Issue by remcqueen1999** [ValveSoftware/unity-xr-plugin#50]
I have installed the XR plugin for Unity and the openVR plugin. I am using a valve index kit and when running the game within unity I can see the controller, but I cannot grab objects. I have followed several online tutorials for the XR plugin and for each one I cannot grab objects through the interaction manager. Is this an issue anyone else faced when starting VR development? Is there any additional setup required to use the valve index controllers with XR?

Thanks for any assistance in advance.

**Comment by zite** [comment]
Unfortunately this plugin does not handle input, and is not compatible with the XR Interaction Toolkit. For input you'll need to use SteamVR Input with the SteamVR Unity Plugin Here: https://assetstore.unity.com/packages/tools/integration/steamvr-plugin-32647

For more info see this pinned issue: https://github.com/ValveSoftware/unity-xr-plugin/issues/16
