### ISSUE TITLE
"Failed to load window layout" error upon starting project with OpenVR XR plugin installed and Project Settings window docked

### ISSUE THREAD

**Issue by Clavus** [ValveSoftware/unity-xr-plugin#51]
This took a while to find, it's been plaguing me for ages. I've also send this bug report to Unity via the editor's bug submission form, but I'm also submitting it here in case it's up to Valve to fix:

**What happens**

![image](https://user-images.githubusercontent.com/670995/94350630-4a5e2680-0050-11eb-942d-677c25505155.png)

I consistently got the "Failed to load window layout" message upon opening my project. After much experimentation I found that it was caused by (a) the Project Settings window being docked the last time I shut down the editor and (2) the OpenVR XR plugin being installed. Installing this plugin adds the OpenVR entry in the "XR Plug-in Management" group in the Project Settings so I assume something is going wrong there.

**How we can reproduce it**

- Create a new project
- Install XR Plugin Management package
- Install the OpenVR XR Plugin
- In the editor, open and dock the Project Settings window somewhere
- Close the Unity editor
- Re-open the project from the Unity Hub
- Observe the error

**Comment by kisak-valve** [comment]
Hello @Clavus, this issue is already being tracked at #35. Closing as a duplicate.
