### ISSUE TITLE
unity, steamVR plugin, publish to webGL, problem with 2019 migrated to 2020

### ISSUE THREAD

**Issue by jensteinkamp** [ValveSoftware/unity-xr-plugin#53]
When I migrate a 2019 project to 2020 SteamVR is not happy. I am publishing to webGL.

MY steps:
Make a copy of the entire project to a new folder

Delete SteamVR and SteamVR_Resources folders and meta files from Assets

ADD the new project to the Hub

Change the Unity Version to 2020.1.6f1

Confirm the upgrade.

XR error message again, even though I deleted SteamVR

Import SteamVR

It automatically set up the XR plugin for me.

Tried publishing it listed 151 errors. Then tried to update itself.

Nothing published

It made a SteamVR Resources folder

This seems to happen with any file I try. It is very easy to reproduce.

**Comment by zite** [comment]
I don't think this plugin supports webgl since webgl doesn't support native dlls.

**Comment by jensteinkamp** [comment]
The plugin works wonderfully with webGL, except for this recent error. I am using the amazing SteamVR emulator to publish projects to webGL using Unity, SteamVR has so many amazing tools. This has been a great resource for teaching during Covid-19.  some examples:
https://classes.dma.ucla.edu/Fall20/156-1/projects/examples/A_vote_primitives_player
jsteinkamp.com/home
Here are some notes on how to setup a webGL with your software:
http://users.design.ucla.edu/~cariesta/3DCourseNotes/html/webgl_post_process.html

**Comment by zite** [comment]
What was the resolution here? I'm surprised it works with webgl, but that's great 🙂

**Comment by jensteinkamp** [comment]
Thanks! I was surprised too, with Covid I had some time to experiment, it was a little tricky to get post processing ambient occlusion to work. The resolution is based on the browser size because I use this plugin from github: better-unity-webgl-template
https://github.com/greggman/better-unity-webgl-template
I imagine my bug listed might occur with VR as well when migrating from Unity 2019 to 2020, I did not test it.

**Comment by jensteinkamp** [comment]
Can you let me know if the problem can be fixed?
