### ISSUE TITLE
Plugin functions in editor, but crashes on launch in 32-bit build

### ISSUE THREAD

**Issue by lachlansleight** [ValveSoftware/unity-xr-plugin#64]
Stumbled upon this by accident when testing something else - I don't really need 32 bit builds but thought I should put up an issue anyway. 

Obviously things run fine in the 64-bit editor, but when I open a build I'm seeing the Unity crash handler pop up, before the main app window opens to a hung black screen.

### Steps to Reproduce

1. Create a new Unity project (version 2020.1.11f1)
2. Add the Unity XR Management package from the Package Manager
3. Import the OpenVR XR Plugin package from this repo
4. Ensure OpenVR Loader is active in the Project Settings
5. In the SampleScene (which just has a Main Camera and Directional Light), add a TrackedPoseDriver to the Main Camera, and create two cubes with a TrackedPoseDriver to follow the left and right controllers respectively
6. Build the app and run it

**Comment by zite** [comment]
Hi, thanks for reporting the issue. I believe I've fixed this in the latest release. You're welcome to give it a try and let me know if it solves the problem.
https://github.com/ValveSoftware/unity-xr-plugin/releases/tag/v1.1.1b

**Comment by kisak-valve** [comment]
Closing per the last comment.
