### ISSUE TITLE
How to get the current refresh rate of a headset? 

### ISSUE THREAD

**Issue by hookmanuk** [ValveSoftware/unity-xr-plugin#66]
There is a function in Unity to get the refresh rate of the headset, but it returns 0 when using this plugin with the Index.

https://docs.unity3d.com/ScriptReference/XR.XRDevice-refreshRate.html

Is there any other way to get the correct refresh rate?

(note I am using an old version of this plugin due to input support being dropped. Apologies if it has been fixed in recent versions)

**Comment by zite** [comment]
Hi, thanks for reporting the issue. I've added this to the latest release. You're welcome to give it a try and let me know if it solves the problem.
https://github.com/ValveSoftware/unity-xr-plugin/releases/tag/v1.1.1b

**Comment by kisak-valve** [comment]
Closing per the last comment.
