### ISSUE TITLE
DX12 support

### ISSUE THREAD

**Issue by m0nsky** [ValveSoftware/unity-xr-plugin#68]
Hi guys,

I've been working with DX12 (using real-time ray tracing) in VR for a while, however, since Unity 2020.1.0a15, we've had to switch to the new XR plug-in management. 

![oXDur4m](https://user-images.githubusercontent.com/8625305/101163072-7e972a00-3633-11eb-83db-5e776a11cc83.gif)

After transitioning to the new com.valve.openvr package, we've lost DX12 support, but the old (working) package has already been deprecated.

I tried to hack in the old package in a modern editor (2020.1, 2020.2, 2021.1) and forcing the XR settings to read only to stop it from updating but no luck. I'm afraid we're stuck in a broken migration process here.

![2ycPNmh](https://user-images.githubusercontent.com/8625305/101163192-9f5f7f80-3633-11eb-8a2f-55e472d5ce33.jpg)

**Comment by zite** [comment]
Unfortunately this is a Unity feature that we don't control. I'd recommend letting them know about your interest in this feature.
