### ISSUE TITLE
Request: Controller & Tracker Pogo Pin Input

### ISSUE THREAD

**Issue by nocanwin** [ValveSoftware/unity-xr-plugin#7]
Can you please include support for tracker input via pogo pins? It's been quite the pain point getting them to work in SteamVR if you have controllers and trackers running at the same time. It would be great if they worked out of the box with the new xr plugin.

**Comment by nocanwin** [comment]
specifically I'd like to be able to query the trigger input. Something like below

```
float triggerValue = 0;
List<InputDevice> inputDevices = new List<InputDevice>();
InputDevices.GetDevicesAtXRNode(XRNode.HardwareTracker, inputDevices);
for (int i = 0; i < inputDevices.Count; i++)
{
     inputDevices[i].TryGetFeatureValue(CommonUsages.trigger, out triggerValue);
}
```

**Comment by zite** [comment]
This plugin no longer supports the unity input system. For input you'll need to use SteamVR Input via the SteamVR Unity Plugin. We hope this will be consolidated with OpenXR.
