### ISSUE TITLE
Can't build for WebXR when OpenVR XR plugin is in project

### ISSUE THREAD

**Issue by yanoty3d** [ValveSoftware/unity-xr-plugin#71]
Similar to #33 
I can't build for WebXR in a project with OpenVR XR plugin because I get these errors

```
Plugin 'ucrtbased.dll' is used from several locations:
 Packages/com.valvesoftware.unity.openvr/Runtime/x64/ucrtbased.dll would be copied to <PluginPath>/ucrtbased.dll
 Packages/com.valvesoftware.unity.openvr/Runtime/x86/ucrtbased.dll would be copied to <PluginPath>/ucrtbased.dll
Please fix plugin settings and try again.

UnityEditor.Modules.DefaultPluginImporterExtension:CheckFileCollisions(String)
UnityEditorInternal.PluginsHelper:CheckFileCollisions(BuildTarget)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
```

I tried Version 1.1.1 but makes no difference.

I would appreciate any helps or suggestions!

**Comment by zite** [comment]
What platform are you building for? Do you have a barebones example project you can share?

**Comment by yanoty3d** [comment]
It is for WebGL. I will try to create a barebone project.

**Comment by yanoty3d** [comment]
I created an empty project on Unity 2020.1.17.f1 and changed the build target to WebGL. Put an empty scene into "Scenes in Build" and start building and get the same error.

**Comment by zite** [comment]
Give this a try: https://github.com/ValveSoftware/unity-xr-plugin/releases/tag/v1.1.2b

**Comment by yanoty3d** [comment]
I tried it and it has worked! Many thanks.
