### ISSUE TITLE
No controllers or input in 2019.4

### ISSUE THREAD

**Issue by Mouledoux** [ValveSoftware/unity-xr-plugin#84]
SteamVR Controllers are not appearing in builds, and no input is being relayed
Both in Legacy VR, and Unity XR
LWRP, and default rendering

**Comment by PioZurID** [comment]
I'm having a similar issue, but only if I launch the game from desktop, with Steam VR being OFF. If Steam VR is ON, the game works fine and controllers are visible in the game. Could you confirm if that's also the way it work for you?

**Comment by Mouledoux** [comment]
@PioZurID
Yes, my issue was also resolved here [https://github.com/ValveSoftware/steamvr_unity_plugin/issues/947]
SteamVR needs to be on for the controllers, and should normally launch itself if your project has VR.
Check your SteamVR_Settings.asset in SteamVR>Resources
There's an "Auto Enable VR" option that when on, will start SteamVR automatically on launch.

**Comment by PioZurID** [comment]
Thanks for your answer! Unfortunately my project is already configured like this. Steam_VR does launch with my game, but the controller's can't be found if Stem_VR wasn't running before the game was launched. Must be a different issue then. Thank again!
