### ISSUE TITLE
Installer Package OpenVR-XR-Plugin-Installer.unitypackage Not Working (2020.3.0f1)

### ISSUE THREAD

**Issue by charlicopter** [ValveSoftware/unity-xr-plugin#85]
Running OpenVR-XR-Plugin-Installer.unitypackage in 2020.3.0f1 throws error:

Error adding new version of OpenVR package.:
	Unable to add package [com.valvesoftware.openvr]:
  Package [com.valvesoftware.openvr] cannot be found

**Comment by zite** [comment]
Yeah we took that unitypackage down as it is an old version that no longer works. Please use this package: https://github.com/ValveSoftware/unity-xr-plugin/releases/tag/v1.1.4 Or pick up the SteamVR Unity Plugin which includes it: https://github.com/ValveSoftware/steamvr_unity_plugin/releases
